### ISSUE TITLE
🚀【聘】到店技术-高级前端工程师-终端

### ISSUE THREAD

**Issue by jiangtao** [jiangtao/blog#29]
#### 业务介绍：
我们服务于美团到店门票度假业务，致力于为**消费者提供更好的游玩体验**，同时我们也帮助**商家提升综和收益及经营效率**。美团门票自2015年成立以来，形成了以景点门票为核心，涉及周边游、跟团等多种业务的**综合度假服务在线平台**。覆盖全国约**330城市**，约**2万**景点。连续3年稳居中国在线门票出票量行业第一。
#### 技术挑战：
* **小程序体验及工程化**：小程序是门票度假 C 端业务核心载体，针对景区环境复杂性、人群多样性的特点，探索和建设*小程序性能体验优化方案*，包括不限于打开速度、首屏时间、交互体验、弱网优化、无障碍化等；同时搭建和完善小程序工程化体系，建设行业领先的小程序研发运维能力，追求质量、效率并重。

* **大数据配置化平台**：伴随着业务地快速发展，越来越多的泛大数据可视化以不同的形式在各种业务场景中落地，研发侧基于端到端深度合作，提供丰富多样的可视化组件，通过建设配置化平台帮助业务快速落地承载海量数据的可视化报表。

* **度量监控体系化**：到店业务快速发展，对技术团队效率、应用的质量性能要求越来越高，我们面向到店终端建设度量监控平台，覆盖核心应用上百，给用户提供（*巡检、趋势、异常管理*）等能力，以此辅助用户发现、分析并解决问题。通过指标衡量团队的研发效率、以及应用的质量性能。

#### 岗位职责：
1. 参与到店门票度假业务终端研发工作，包括不限于 *小程序、H5、Web、App PC中后台* 等开发。
2. 参与*小程序体验及工程化*、*大数据配置化平台、度量监控体系化*，等重点技术项目的开发。
3. 关注前端前沿技术，基于业务场景落地实践，持续推进和提升研发效率、完善技术体系。

#### 岗位要求：
* 前端基础知识扎实，熟练掌握 *TS/ES、HTML、CSS*。
* 熟悉并掌握至少一种 MVVM 框架，如: *Vue/React/Angular*，Vue优先。
* 熟悉前端工程化和构建工具（*npm/Vite/Webpack*）、构建流程及原理等。
* 具备微信小程序开发经验，熟练掌握主要组件、API 的使用。
* 熟悉使用过 *NodeJS* 主流开发框架 (*Koa、Egg*) 或具备其他后端语言经验。
* 2年以上前端开发经验（自认能力突出者不受此限）。

#### 优先条件：
* 有搭建服务、*IDE*插件、*LowCode* 项目经验优先。
* 有跨端开发经验，熟悉 *chameleon/Taro/kbone* 等开源框架。
* 有个人开源项目或参与过开源项目的维护、个人技术博客等。

#### 团队格调：
* **关注健康**：团队不推崇加班文化，鼓励跑步、游泳、爬山等运动。
* **氛围活跃**：有妹子有暖男有活宝，整体氛围活跃，两周一聚餐，季度有团建。
* **学习成长**：互联网+大学课程等你来学习，站在巨人肩膀上可以走得更远。

> 有意者发送简历至:*huangjiangtao@meituan.com*

**Comment by alanerzhao** [comment]
yeah
